### ISSUE TITLE
Problems remain after file closure

### ISSUE THREAD

**Issue by tinygiant98** [PhilippeChab/nwscript-ee-language-server#33]
I've notice an anomaly that I haven't exactly nailed down the cause of yet, but I believe it's related to problems that are identified through the diagnostics provider which remain on the problems panel after the associated file is closed.  There appears to be some cross-talk in the reported problems that assigns a problem from one file (a closed file) to another file (an open file).  In the following screenshot, you can see that this error is obviously misplaced from a previously open file.

![image](https://user-images.githubusercontent.com/56231301/182009921-750dc4ad-0222-44ae-9c66-0db8bcf586a8.png)

Additionally, my problems panel has problems from previously open file which are no longer open.  Is this desired behavior or is there an option to clear the problems panel when the offending file is closed?

**Comment by PhilippeChab** [comment]
The error in the screenshot happens when the compiler is unable to resolve an include. This should never happen normally as the includes directories of the compiled file are automatically passed to the compiler along with the `-i` option. The workspace was in an anormal state at this moment. 

I would need more details to be able to help you. Could you give me more context on how this happened?

**Comment by tinygiant98** [comment]
I'll attempt to find a way to recreate it and send you whatever details I can obtain.  Thanks!

**Comment by tinygiant98** [comment]
Ive seen this issue multiple times, but I'm unable to nail down exactly what causes it. I'll close for now until I can reliably rebate the behavior.
