### ISSUE TITLE
Constant Regex not recognizing legal constant

### ISSUE THREAD

**Issue by tinygiant98** [PhilippeChab/nwscript-ee-language-server#36]
I'm sure this regex is standard, so I may not be following the normal rules for constant definition, but here's what I'm seeing based on the following `constant.language.nss` scope in `nwscript-ee.tmLanguage.json` -> `"\\b[A-Z]+(_[A-Z]+)*(_[a-zA-Z0-9]+){0,1}(?!\\()\\b"`:

`H2_BLEED_TIMER_SCRIPT` -> Not a constant token (because of the `2` in the first group)
`H_2BLEED_TIMER_SCRIPT` -> Not a constant token (because of the `2` in the second group)
`H_BLEED_2TIMER_SCRIPT` -> Not a constant token (because of the `2` in the third group)
`H_BLEED_TIMER_2SCRIPT` -> Valid constant token (numbers allowed in this capture group)

Also, any constant that would otherwise meet the definition, but starts with an underscore (i.e. `_H2_BLEED_TIMER`) is also unrecognized.  Are these generally accepted rules (numbers nearly never allowed and underscores can't start), even though they're acceptable in nwscript?  If so, no bid deal, I'll work within the normal rules.  If not, can the regex be changed to reflect these limitations?

I don't know much about regex, but this seems to work (but again, as long as it's valid in the greater language context, which I'm no expert at):  `\\b_*([A-Z])+([_a-zA-Z0-9])*(?!\\()\\b`

**Comment by PhilippeChab** [comment]
Hey!

The constant tokenization for NWScript is a complicated problem, because the keyword `const` was introduced later on in the language and variable in the global scope without the `const` keyword can actually be treated as a constant - all the constants in `nwscript.nss` for example. If it was not the case, we could have just have a regex that detects the const keyword and pick the third capturing group as the constant name.

We need to be careful with this, because variables could be treated as constants and vice-versa.

I will try to tweak the regex so that it is more permissive.
